controller_list:
  - name: fake_arm_group_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_end_group_controller
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: arm_group
    pose: home_pose
  - group: end_group
    pose: grip_close_1