joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

end_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - gripper_finger1_joint
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10