obstacle_range: 6.0
raytrace_range: 8.5

footprint: [[-0.27, -0.3], [-0.27, 0.300], [0.27, 0.300], [0.27, -0.300]]
#robot_radius: 0.17

inflation_radius: 0.4
cost_scaling_factor: 5

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: obito/laser/scan, marking: true, clearing: true}
