local_costmap:
  global_frame: map
  robot_base_frame: obito_base

  update_frequency: 5 #10.0
  publish_frequency: 5 #10.0
  transform_tolerance: 1.5  

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05